name: Sync GitHub Repo to AWS CodeCommit

on:
  push:
    branches:
      - main  # Replace with your branch name if different

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-southeast-1  # Adjust if necessary

    - name: Install Git and AWS CLI
      run: |
        sudo apt-get update
        sudo apt-get install git -y
        sudo apt-get install awscli -y

    - name: Configure Git to use AWS CodeCommit credential helper
      run: |
        git config --global credential.helper '!aws codecommit credential-helper $@'
        git config --global credential.UseHttpPath true

    - name: Add CodeCommit remote and push
      run: |
        git remote add codecommit https://git-codecommit.ap-southeast-1.amazonaws.com/v1/repos/test-player-be
        git push --force codecommit main:main
